/**
 * HEC-recognised universities and degree-awarding institutes, grouped by
 * province / territory, for the University dropdown. Source: hec.gov.pk
 * "Recognised Universities" (retrieved 1 Oct 2026), 283 institutions.
 */
export const HEC_UNIVERSITIES: { province: string; universities: string[] }[] = [
  {
    province: "Punjab",
    universities: [
      "Al-Karam International Institute, Bhera",
      "Ali Bin Usman Institute, Multan",
      "Ali Institute of Education",
      "Baba Guru Nanak University, Nankana Sahib",
      "Bahauddin Zakariya University",
      "Beaconhouse National University",
      "Cholistan University of Veterinary and Animal Sciences, Bahawalpur",
      "Emerson University, Multan",
      "Faisalabad Medical University, Faisalabad",
      "Fatima Jinnah Medical University, Lahore",
      "Fatima Jinnah Women University, Rawalpindi",
      "Forman Christian College",
      "Ghazi National Institute of Engineering and Sciences, Dera Ghazi Khan",
      "Ghazi University, Dera Ghazi Khan",
      "GIFT University",
      "Global Institute, Lahore [HEC-NOC SUSPENDED] (ADMISSIONS HAVE BEEN STOPPED BY HEC FROM FALL 2016)",
      "Government College for Women University, Sialkot",
      "Government College University, Faisalabad",
      "Government College University, Lahore",
      "Government College Women University, Faisalabad",
      "Government Sadiq College Women University",
      "Grand Asian University, Sialkot",
      "Hajvery University",
      "HITEC University",
      "Imperial College of Business Studies",
      "Information Technology University of the Punjab",
      "Institute for Art and Culture",
      "Institute of Management Sciences",
      "International Institute of Science, Arts and Technology, Gujranwala",
      "Islamia University",
      "Khawaja Freed University of Engineering & Information Technology, Rahim Yar Khan",
      "King Edward Medical University",
      "Kinnaird College for Women",
      "Kohsar University, Murree",
      "Lahore College for Women University",
      "Lahore Garrison University",
      "Lahore Leads University",
      "Lahore School of Economics",
      "Lahore University of Biological and Applied Sciences, Lahore",
      "Lahore University of Management Sciences",
      "Minhaj University",
      "Mir Chakar Khan Rind University of Technology, Dera Ghazi Khan",
      "Muhammad Nawaz Shareef University of Agriculture",
      "Muhammad Nawaz Sharif University of Engineering & Technology",
      "Mukabbir University of Science & Technology, Gujrat",
      "Multan University of Science & Technology, Multan",
      "Namal University, Mainwali",
      "National College of Arts",
      "National College of Business Administration & Economics",
      "National Excellence Institute (NEI), Rawalpindi",
      "National Institute of Technology, Lahore",
      "National Textile University",
      "National University of Medical Sciences",
      "National University of Pakistan",
      "NFC Institute of Engineering & Technology",
      "Nippon Institute of Advanced Sciences, Sheikhupura",
      "Nishtar Medical University, Multan",
      "Nur International University",
      "Pakistan Global Institute, Rawat",
      "Pakistan Institute of Fashion & Design",
      "Pir Mehr Ali Shah Arid Agriculture University",
      "Punjab Tianjin University of Technology, Lahore",
      "Qarshi University",
      "Quaid e Azam Institute of Management Sciences Sargodha",
      "Rashid Latif Khan University, Lahore",
      "Rawalpindi Medical University",
      "Rawalpindi Women University, Rawalpindi",
      "South Punjab Institute of Science and Technology, Dera Ghazi Khan",
      "Thal University, Bhakkar",
      "The Ganj Shakar University, Pakpattan",
      "The Green International University, Lahore",
      "The Superior University",
      "The University of Faisalabad",
      "The Women University",
      "TIMES University, Multan",
      "University of Agriculture",
      "University of Central Punjab",
      "University of Chakwal, Chakwal",
      "University of Chenab, Gujrat",
      "University of Child Health Sciences, Lahore",
      "University of Education",
      "University of Engineering & Technology, Taxila",
      "University of Gujrat",
      "University of Health Sciences",
      "University of Home Economics, Lahore",
      "University of Jhang",
      "University of Kamalia",
      "University of Lahore",
      "University of Layyah",
      "University of Management & Technology",
      "University of Mianwali",
      "University of Narowal",
      "University of Okara",
      "University of Rasul-Mandi Bahauddin",
      "University of Sahiwal",
      "University of Sargodha",
      "University of Science and Technology, Lahore",
      "University of Sialkot, Sialkot",
      "University of South Asia",
      "University of Southern Punjab",
      "University of the Punjab",
      "University of Veterinary & Animal Sciences",
      "University of Wah",
      "Virtual University of Pakistan",
    ],
  },
  {
    province: "Sindh",
    universities: [
      "Adam Institute of Social & Management Science (AISMS), Karachi",
      "Aga Khan University",
      "Al-Ghazali University",
      "Al-Kawthar University, Karachi",
      "Aror University of Art, Architecture, Design and Heritage, Sukkur",
      "Baqai Medical University",
      "Begum Nustrat Bhutto Women University, Sukkur",
      "Benazir Bhutto Shaheed University Lyari",
      "Benazir Bhutto Shaheed University of Technology & Skill Development, Khairpur Mirs",
      "Commecs Institute of Business & Emerging Sciences",
      "Dadabhoy Institute of Higher Education",
      "Dawood University of Engineering & Technology",
      "Denning Institute of Technology and Entrepreneurship, Karachi",
      "DHA Suffa University",
      "DOW University of Health Sciences",
      "Emaan Institute of Management & Sciences, Karachi",
      "Gambat Institute of Medical Sciences",
      "Government College University, Hyderabad",
      "Greenwich University",
      "Habib University",
      "Hamdard University",
      "Hands-Institute of Development Studies, Karachi",
      "Hyderabad Institute for Technology & Management Sciences",
      "Ibn-e-Sina University, Mirpurkhas",
      "ILMA University",
      "Indus University",
      "Indus Valley School of Art & Architecture",
      "Institute of Business Administration",
      "Institute of Business Management",
      "Iqra University",
      "Isra University",
      "Jinnah Sindh Medical University",
      "Jinnah University for Women",
      "Karachi Institute of Economics & Technology",
      "Karachi Institute of Technology and Entrepreneurship (KITE), Karachi",
      "Karachi Metropolitan University, Karachi",
      "Karachi School of Business and Leadership",
      "KASB Institute of Technology",
      "Liaquat University of Medical & Health Sciences",
      "Malir University of Science & Technology, Karachi",
      "Mehran University of Engineering & Technology",
      "Metropolitan University Karachi",
      "Millennium Institute of Technology and Entrepreneurship, Karachi",
      "Muhammad Ali Jinnah University",
      "NED University of Engineering & Technology",
      "Newport Institute of Communications & Economics",
      "PAF Air War College Institute, Karachi",
      "Pakistan Naval Academy",
      "Peoples University of Medical & Health Sciences for Women",
      "Preston Institute of Management, Science & Technology",
      "Preston University, Karachi",
      "Quaid-e-Awam University of Engineering, Sciences & Technology",
      "Saifee Burhani University, Karachi",
      "Salim Habib University (Former Barret Hodgson University), Karachi",
      "Shah Abdul Latif University",
      "Shaheed Allah Buksh Soomro University of Arts, Design and Heritages, Jamshoro",
      "Shaheed Benazir Bhutto City University",
      "Shaheed Benazir Bhutto Dewan University",
      "Shaheed Benazir Bhutto University of Veterinary & Animal Sciences",
      "Shaheed Benazir Bhutto University, Shaheed Benazirabad",
      "Shaheed Mohtarma Benazir Bhutto Medical University",
      "Shaheed Zulfikar Ali Bhutto Institute of Science & Technology",
      "Shaheed Zulfiqar Ali Bhutto University of Law",
      "Sindh Agriculture University, Tandojam",
      "Sindh Institute of Management & Technology",
      "Sindh Institute of Medical Sciences",
      "Sindh Madresatul Islam University",
      "Sir Syed University of Engineering & Technology",
      "Sohail University, Karachi",
      "Sukkur IBA University",
      "Textile Institute of Pakistan",
      "The Nazeer Hussain University",
      "The Shaikh Ayaz University, Shikarpur Sindh",
      "The Sindh Institute of Physical Medicine and Rehabilitation, Karachi",
      "The University of Larkano",
      "The University of Mirpurkhas",
      "UIT University, Karachi",
      "University of Art and Culture, Jamshoro",
      "University of Karachi",
      "University of Modern Sciences, Tando Muhammad Khan",
      "University of Sindh",
      "University of Sufism and Modern Sciences, Bhitshah Sindh",
      "Zia-ud-Din University",
    ],
  },
  {
    province: "Khyber Pakhtunkhwa",
    universities: [
      "Abasyn University",
      "Abbottabad University of Science and Technology (AUST)",
      "Abdul Wali Khan University",
      "Bacha Khan University",
      "Brains Institute Peshawar",
      "CECOS University of Information Technology & Emerging Sciences",
      "City University of Science and Information Technology",
      "Gandhara University",
      "Ghulam Ishaq Khan Institute of Engineering Sciences & Technology",
      "Gomal University",
      "Hazara University",
      "Institute of Management Science",
      "Iqra National University",
      "Islamia College Peshawar",
      "Kalam Bibi International Women Institute, Bannu",
      "Khushal Khan Khattak University",
      "Khyber Medical University",
      "Kohat University of Science and Technology",
      "Northern University",
      "Pak-Austria Fachhochschule Institute of Applied Sciences and Technology, Haripur",
      "Pakistan Military Academy",
      "Preston University, Kohat",
      "Qurtaba University of Science & Information Technology",
      "Sarhad University of Science & Information Technology",
      "Shaheed Benazir Bhutto University",
      "Shaheed Benazir Bhutto Women University",
      "Shuhada-e-Army Public School University of Technology, Nowshera",
      "The University of Agriculture, D. I. Khan",
      "The University of Agriculture, Peshawar",
      "The University of Agriculture, Swat",
      "The University of Veterinary & Animal Sciences, Swat",
      "University of Buner",
      "University of Chitral",
      "University of Engineering & Technology",
      "University of Engineering & Technology (UET), Mardan",
      "University of Engineering and Applied Sciences, Swat",
      "University of FATA",
      "University of Haripur",
      "University of Lakki Marwat",
      "University of Malakand",
      "University of Peshawar",
      "University of Science & Technology",
      "University of Shangla",
      "University of Swabi",
      "University of Swat",
      "Woman University Swabi",
      "Women University Mardan",
    ],
  },
  {
    province: "Balochistan",
    universities: [
      "Al-Hamd Islamic University",
      "Balochistan University of Engineering & Technology",
      "Balochistan University of Information Technology, Engineering & Management Sciences (BUITEMS)",
      "Lasbela University of Agriculture, Water & Marine Sciences",
      "Mir Chakar Khan Rind University, Sibi Balochistan",
      "Sardar Bahadur Khan Women University",
      "The Bolan University of Medical and Health Sciences, Quetta",
      "University of Balochistan",
      "University of Gwadar",
      "University of Loralai",
      "University of Makran, Panjgur",
      "University of Turbat",
    ],
  },
  {
    province: "Islamabad Capital Territory",
    universities: [
      "Air University",
      "Allama Iqbal Open University",
      "Bahria University",
      "Capital University of Science & Technology",
      "COMSATS University, Islamabad",
      "Dar-ul-Madina International University, Islamabad",
      "Federal Urdu University of Arts, Sciences & Technology",
      "Foundation University",
      "Health Services Academy (HSA), Islamabad",
      "Ibadat International University, Islamabad",
      "Institute of Space Technology",
      "International Islamic University",
      "Islamabad University of Health Sciences and Emerging Technologies (IUHT) ,Islamabad",
      "MY University",
      "National Defense University",
      "National Skills University, Islamabad",
      "National University of Computer & Emerging Sciences",
      "National University of Modern Languages",
      "National University of Sciences & Technology",
      "National University of Technology (NUTECH), Islamabad",
      "Pakistan Institute of Development Economics",
      "Pakistan Institute of Engineering & Applied Sciences",
      "Quaid-i-Azam University",
      "Riphah International University",
      "Shaheed Zulfiqar Ali Bhutto Medical University",
      "Shifa Tameer-e-Millat University",
      "Sir Syed (CASE) Institute of Technology, Islamabad",
    ],
  },
  {
    province: "Gilgit-Baltistan",
    universities: [
      "Karakurum International University",
      "University of Baltistan, Skardu",
    ],
  },
  {
    province: "Azad Jammu & Kashmir",
    universities: [
      "Al-Khair University",
      "Mirpur University of Science & Technology",
      "Mohi-ud-Din Islamic University",
      "The Azad Jammu & Kashmir University of Bhimber",
      "University of Azad Jammu & Kashmir",
      "University of Kotli",
      "University of Poonch",
      "Women University of Azad Jammu & Kashmir",
    ],
  },
];

export const ALL_HEC_UNIVERSITIES = HEC_UNIVERSITIES.flatMap((group) => group.universities);
