/**
 * Cities of Pakistan, grouped by province / territory, for the City dropdown.
 * Built from the 2023 census city list, every district headquarters, and every
 * city with an HEC-recognised university (sources: Pakistan Bureau of Statistics
 * via Wikipedia, hec.gov.pk). 228 cities.
 */
export const PAKISTAN_CITIES: { province: string; cities: string[] }[] = [
  {
    province: "Punjab",
    cities: [
      "Ahmedpur East",
      "Arif Wala",
      "Attock",
      "Bahawalnagar",
      "Bahawalpur",
      "Bhakkar",
      "Bhalwal",
      "Bhera",
      "Burewala",
      "Chakwal",
      "Chichawatni",
      "Chiniot",
      "Chishtian",
      "Daska",
      "Dera Ghazi Khan",
      "Dipalpur",
      "Faisalabad",
      "Farooqabad",
      "Ferozwala",
      "Gojra",
      "Gujar Khan",
      "Gujranwala",
      "Gujrat",
      "Hafizabad",
      "Haroonabad",
      "Hasilpur",
      "Haveli Lakha",
      "Jalalpur Jattan",
      "Jampur",
      "Jaranwala",
      "Jatoi",
      "Jauharabad",
      "Jhang",
      "Jhelum",
      "Kamalia",
      "Kamoke",
      "Kasur",
      "Khanewal",
      "Khanpur",
      "Kharian",
      "Khushab",
      "Kot Abdul Malik",
      "Kot Addu",
      "Kot Radha Kishan",
      "Lahore",
      "Lala Musa",
      "Layyah",
      "Lodhran",
      "Ludhewala Waraich",
      "Mailsi",
      "Mandi Bahauddin",
      "Mian Channu",
      "Mianwali",
      "Multan",
      "Muridke",
      "Murree",
      "Muzaffargarh",
      "Nankana Sahib",
      "Narowal",
      "Okara",
      "Pakpattan",
      "Pasrur",
      "Pattoki",
      "Phool Nagar",
      "Rahim Yar Khan",
      "Rajanpur",
      "Rawalpindi",
      "Rawat",
      "Renala Khurd",
      "Sadiqabad",
      "Sahiwal",
      "Sambrial",
      "Samundri",
      "Sangla Hill",
      "Sargodha",
      "Shakargarh",
      "Sheikhupura",
      "Shujabad",
      "Sialkot",
      "Talagang",
      "Taunsa",
      "Taxila",
      "Toba Tek Singh",
      "Vehari",
      "Wah Cantonment",
      "Wazirabad",
    ],
  },
  {
    province: "Sindh",
    cities: [
      "Badin",
      "Bhit Shah",
      "Bholari",
      "Dadu",
      "Ghotki",
      "Hyderabad",
      "Jacobabad",
      "Jamshoro",
      "Kamber Ali Khan",
      "Kandhkot",
      "Karachi",
      "Khairpur",
      "Kotri",
      "Larkana",
      "Matiari",
      "Mirpur Khas",
      "Mirpur Mathelo",
      "Mithi",
      "Moriro Mirbahar",
      "Moro",
      "Naushahro Feroze",
      "Nawabshah",
      "Qambar",
      "Sanghar",
      "Shahdadkot",
      "Shahdadpur",
      "Shikarpur",
      "Sujawal",
      "Sukkur",
      "Tando Adam",
      "Tando Allahyar",
      "Tando Muhammad Khan",
      "Thatta",
      "Umerkot",
    ],
  },
  {
    province: "Khyber Pakhtunkhwa",
    cities: [
      "Abbottabad",
      "Allai Valley",
      "Alpuri",
      "Bannu",
      "Barikot",
      "Batkhela",
      "Battagram",
      "Booni",
      "Buner",
      "Charsadda",
      "Chitral",
      "Daggar",
      "Dasu",
      "Dera Ismail Khan",
      "Dir",
      "Ghalanai",
      "Hangu",
      "Haripur",
      "Judba",
      "Kabal",
      "Kalaya",
      "Karak",
      "Khar",
      "Kohat",
      "Kolai",
      "Lakki Marwat",
      "Landi Kotal",
      "Mansehra",
      "Mardan",
      "Mingora",
      "Miranshah",
      "Nowshera",
      "Parachinar",
      "Pattan",
      "Peshawar",
      "Saidu Sharif",
      "Shabqadar",
      "Shangla",
      "Spinkai",
      "Swabi",
      "Swat",
      "Tank",
      "Timergara",
      "Wana",
      "Wari",
    ],
  },
  {
    province: "Balochistan",
    cities: [
      "Awaran",
      "Barkhan",
      "Chaman",
      "Dalbandin",
      "Dera Allahyar",
      "Dera Bugti",
      "Dera Murad Jamali",
      "Dhadar",
      "Duki",
      "Gandava",
      "Gwadar",
      "Harnai",
      "Hub",
      "Jungle Pir Alizai",
      "Kalat",
      "Kharan",
      "Khuzdar",
      "Kohlu",
      "Lasbela",
      "Loralai",
      "Mastung",
      "Musa Khel Bazar",
      "Nushki",
      "Panjgur",
      "Pishin",
      "Qilla Saifullah",
      "Quetta",
      "Sherani",
      "Sibi",
      "Sohbatpur",
      "Surab",
      "Turbat",
      "Usta Muhammad",
      "Uthal",
      "Washuk",
      "Zhob",
      "Ziarat",
    ],
  },
  {
    province: "Islamabad Capital Territory",
    cities: [
      "Islamabad",
    ],
  },
  {
    province: "Gilgit-Baltistan",
    cities: [
      "Chilas",
      "Dambudas",
      "Darel",
      "Eidghah",
      "Gahkuch",
      "Gilgit",
      "Karimabad",
      "Khaplu",
      "Nagarkhas",
      "Phander",
      "Shigar",
      "Skardu",
      "Tangir",
      "Tolti",
    ],
  },
  {
    province: "Azad Jammu & Kashmir",
    cities: [
      "Athmuqam",
      "Bagh",
      "Bhimber",
      "Forward Kahuta",
      "Hattian Bala",
      "Kotli",
      "Mirpur",
      "Muzaffarabad",
      "Nerian Sharif",
      "Pallandari",
      "Rawalakot",
    ],
  },
];

export const ALL_PAKISTAN_CITIES = PAKISTAN_CITIES.flatMap((group) => group.cities);
